config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' },
                   path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}

  root "articles#index"

  get "/articles", to: "articles#index"
  resources :products
  resources :chats
  resources :orders
  resources :reviews

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  has_many :message, dependent: :destroy
  validates :id_user, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  has_one :chat
end

app/models/order.rb
class Order < ApplicationRecord
    validates :id_product, presence: true
    validates :order_date, presence: true
    validates :status, presence: true
    validates :id_user, presence: true


"""
colocar validate
"""
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :review, dependent: :destroy
    has_one :order
    has_one :user, through: :order
    validates :name, presence: true
    validates :price, presence: true

  end

app/models/review.rb
class Review < ApplicationRecord
    validates :id_user, presence: true
    validates :id_product, presence: true
    validates :content, presence: true
    validates :grade, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  validates :name, presence: true
  validates :cellphone, presence: true, length: {is: 9}

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: [:user, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  has_many :order
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def index
    @chat = Chat.all
  end

  def show
    @chat = Chat.find(params[:id])
  end

  def create
    @chat = Chat.new(chat_params)
    if @chat.save
      redirect_to chat_path(@chat.id)
    else
      render @chat.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @chat = Chat.find(params[:id_chat])
    if @chat.destroy
      render json: {message: "El chat se eliminó correctamente."}
    else
      render json: @chat.errors, status: :unprocessable_entity
    end
  end

  def chat_params
    params.require(:chat).permit(:id_user)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @chat = Chat.find(message_params[:id_chat])
    @message = @chat.message.create(message(message_params))
    if @message.save
      redirect_to chat_path(@message.id_chat)
    else
      render @chat.errors, status: :unprocessable_entity
    end
  end

  def message_params
    params.require(:message).permit(:content, :id_chat)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    include Devise::Controllers::Helpers

    def order_params
        params.require(:order).permit(:id_product, :id_user, :description, :status, :order_date)
    end


    def index
        @orders = Order.all
    end


    def show
        @orders = Order.where(user_id: params[:id_user])
    end


    def create
        @order = Order.new(order_params)
        @order.user_id = current_user.id # Asignar el id del usuario actual

        if @order.save
          render json: {message: "La orden ha sido recibida"}
        else
          render json: @order.errors, status: :unprocessable_entity
        end
    end
"""
update prox sprint
"""
    def update
        @user = User.find(params[:id_user])
        @order = @user.order.find(params[:id])

        if @order.update(order_params)
            render json: {message: "El estado de la orden se actualizo"}
        else
            render json: @order.errors, status: :unprocessable_entity
        end
    end


    def destroy
        @user = User.find(params[:id_user])
        @order = @user.order.find(params[:id])

        if @order.destroy
            render json: {message: "La orden se eliminó correctamente."}
        else
            render json: @order.errors, status: :unprocessable_entity
        end
    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    if user_signed_in?
      @products = Product.all
    else
      render json: "No has iniciado sesion"
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      render json: {message: "Producto was successfully created."}
    else
      render @product.errors, status: :unprocessable_entity
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to product_url(@product), notice: "Product was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.delete
    redirect_to products_url, notice: "Product was successfully destroyed."
  end

  def product_params
    params.require(:product).permit(:name, :price, :image)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    def review_params
        params.require(:review).permit(:id_user, :id_product, :content, :grade)
    end


    def index
        @reviews = Review.where(id_user: current_user.id)
    end


    def create
        @review = Review.new(review_params)
        
        if @review.save
            render json: {message: "Review was successfully created."}
        else
            render json: @review.errors, status: :unprocessable_entity
          
        end
    end


    def new
        @review = Review.new
        @order = Order.find(params[:id_order])
        @product = Product.find(params[:id_product])
      end

    def update
        @user = User.find(params[:id_user])
        @review = @user.reviews.find(params[:id])

        if @review.update(review_params)
            render json: {message: "Review was successfully updated."}
        else
            render json: @review.errors, status: :unprocessable_entity
        end
    end


    def destroy
        @user = User.find(current_user.id)
        @review = @user.reviews.find(params[:id])

        if @review.delete
            render json: {message: "Review was sucessfully deleted."}
        else
            render json: @review.errors, status: :unprocessable_entity
        end
    end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/chats/_form.html.erb
<%= form_with(model: message) do |chat| %>
    <% if chat.errors.any? %>
      <div style="color: red;font-size: 0.8em;">
        <h2><%= pluralize(chat.errors.count, "error") %> prohibited this message from being saved:</h2>

        <ul>
          <% chat.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <br/>
      <%= form.text_field :content %>
      <br/>
      <%= form.submit class:"button" %>
  <% end %>

app/views/chats/index.html.erb
<p style="color: green"><%= notice %></p>

<a class="button" href="chats/create"> New Chat </a>

<div id="chat">
  <h1> Chat </h1>
  <% @chat.each do |chat| %>
    <td><%= chat %></td>
    <td><%= link_to "Open Chat", chat %></td>
  <% end %>
</div>
<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/chats/show.html.erb
<p style="color: green"><%= notice %></p>

<div id="chat">
  <h1> Chat </h1>
  <% @chat.message.each do |message| %>
    <td><%= message.content %></td>
  <% end %>

  <%= render "messages/form", chat: @chat %>

  <td><%= link_to "Back to Chats", chats %></td>
</div>

app/views/messages/_form.html.erb
<%= form_with(model: message) do |form| %>
    <% if message.errors.any? %>
      <div style="color: red;font-size: 0.8em;">
        <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

        <ul>
          <% message.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <br/>
      <%= form.text_field :content %>
      <%= form.hidden_field :chat_id, :value => chat.id %>
      <br/>
      <%= form.submit class:"button" %>
  <% end %>

app/views/orders/index.html.erb
<p style="color: green"><%= notice %></p>

<div id="products">
  <h1> Products </h1>
  <table class="styled-table">
    <thead>
      <tr>
        <th>Imagen</th>
        <th>Producto</th>
        <th>Precio</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      <% @orders.each do |order| %>
        <% product = Product.find_by(id: order.id_product) %>
        <tr>
          <td><%= image_tag(product.image) %></td>
          <td><%= product.name %></td>
          <td><%= product.price %></td>
          <td><%= order.status %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/orders/show.html.erb
<p style="color: green"><%= notice %></p>

<div id="products">
  <h1> Products </h1>
  <table class="styled-table">
    <thead>
      <tr>
        <th style="width: 25%;">Imagen</th>
        <th style="width: 35%;">Producto</th>
        <th style="width: 20%;">Precio</th>
        <th style="width: 20%;">Status</th>
        <th style="width: 10%;">Acción</th>
      </tr>
    </thead>
    <tbody>
      <% @orders.each do |order| %>
        <% product = Product.find_by(id: order.id_product) %>
        <tr>
          <td><%= product.image %></td>
          <td><%= product.name %></td>
          <td><%= product.price %></td>
          <td><%= order.status %></td>
          <td><%= link_to 'Agregar Review', new_review_path(id_product: product.id, id_order: order.id) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/products/_form.html.erb
<%= form_with(model: @product) do |form| %>
    <br/>
      <%= form.label :name %>
      <%= form.text_field :name %>
      <%= form.label :price %>
      <%= form.number_field :price%>
      <%= form.label :image %>
      <%= form.file_field :image%>
      <br/>
      <%= form.submit class:"button" %>
  <% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<div>
  <%= link_to "Show this Product", @products %> |
  <%= link_to "Back to Products", products_path %>
</div>
<br>
<%= render "form", product: @product %>

app/views/products/index.html.erb
<p style="color: green"><%= notice %></p>

<% if current_user.admin? %>
  <a class="button" href="products/new"> New </a>
<% end %>

<div>
<%= link_to "Chats", "/chats"%>
</div>

<div id="products">
  <h1> Products </h1>
  <table class="styled-table">
    <thead>
      <tr>
        <th>Imagen</th>
        <th>Producto</th>
        <th>Precio</th>
      </tr>
    </thead>
    <tbody>
  <% @products.each do |product| %>
    <tr>
        <td><%= product.image %></td>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= link_to "Show me this Product", product %></td>
    </tr>
  <% end %>
    </tbody>
  </table>
</div>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<% if current_user.admin? %>
  <div>
  <%= link_to "Edit this Product", edit_product_path(@product) %>
  <%= button_to "Destroy", @product, method: :delete, class:"button-2" %>
  </div>
<% end %>

<div>
  <%= link_to "Back to Products", products_path %>
</div>
<table class="styled-table">
  <tr>
    <td><b>Imagen:</b></td>
    <td><%= @product.image %></td>
  <tr>
  <tr>
    <td><b>Producto:</b></td>
    <td><i><%= @product.name %></i></td>
  <tr>
  <tr>
    <td><b>Precio:</b></td>
    <td><i><%= @product.price %></i></td>
  <tr>
</table>

<div>

  <%= button_to "Order Product", orders_path(order: { id_product: @product.id, id_user: current_user.id,
  order_date: Date.today.strftime("%d/%m/%Y"), status: "pending" }), method: :post %>

</div>