config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' },
                   path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}

  root "articles#index"

  get "/articles", to: "articles#index"
  resources :products
  resources :chats
  resources :orders
  resources :reviews

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  has_many :message, dependent: :destroy
  validates :id_user, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  has_one :chat
end

app/models/order.rb
class Order < ApplicationRecord
    validates :id_product, presence: true
    validates :order_date, presence: true
    validates :status, presence: true
    validates :id_user, presence: true


"""
colocar validate
"""
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :review, dependent: :destroy
    has_one :order
    has_one :user, through: :order
    validates :name, presence: true
    validates :price, presence: true

  end

app/models/review.rb
class Review < ApplicationRecord
    validates :id_user, presence: true
    validates :id_product, presence: true
    validates :content, presence: true
    validates :grade, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  validates :name, presence: true
  validates :cellphone, presence: true, length: {is: 9}

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: [:user, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  has_many :order
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def index
    @chat = Chat.all
  end

  def show
    @chat = Chat.find(params[:id])
  end

  def create
    @chat = Chat.new(chat_params)
    if @chat.save
      redirect_to chat_path(@chat.id)
    else
      render @chat.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @chat = Chat.find(params[:id_chat])
    if @chat.destroy
      render json: {message: "El chat se eliminó correctamente."}
    else
      render json: @chat.errors, status: :unprocessable_entity
    end
  end

  def chat_params
    params.require(:chat).permit(:id_user)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @chat = Chat.find(message_params[:id_chat])
    @message = @chat.message.create(message(message_params))
    if @message.save
      redirect_to chat_path(@message.id_chat)
    else
      render @chat.errors, status: :unprocessable_entity
    end
  end

  def message_params
    params.require(:message).permit(:content, :id_chat)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    include Devise::Controllers::Helpers

    def order_params
        params.require(:order).permit(:id_product, :id_user, :description, :status, :order_date)
    end


    def index
        @orders = Order.all
    end


    def show
        @orders = Order.where(user_id: params[:id_user])
    end


    def create
        @order = Order.new(order_params)
        @order.user_id = current_user.id # Asignar el id del usuario actual

        if @order.save
          render json: {message: "La orden ha sido recibida"}
        else
          render json: @order.errors, status: :unprocessable_entity
        end
    end
"""
update prox sprint
"""
    def update
        @user = User.find(params[:id_user])
        @order = @user.order.find(params[:id])

        if @order.update(order_params)
            render json: {message: "El estado de la orden se actualizo"}
        else
            render json: @order.errors, status: :unprocessable_entity
        end
    end


    def destroy
        @user = User.find(params[:id_user])
        @order = @user.order.find(params[:id])

        if @order.destroy
            render json: {message: "La orden se eliminó correctamente."}
        else
            render json: @order.errors, status: :unprocessable_entity
        end
    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    if user_signed_in?
      @products = Product.all
    else
      render json: "No has iniciado sesion"
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      render json: {message: "Producto was successfully created."}
    else
      render @product.errors, status: :unprocessable_entity
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to product_url(@product), notice: "Product was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.delete
    redirect_to products_url, notice: "Product was successfully destroyed."
  end

  def product_params
    params.require(:product).permit(:name, :price, :image)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    def review_params
        params.require(:review).permit(:id_user, :id_product, :content, :grade)
    end


    def index
        @reviews = Review.where(id_user: current_user.id)
    end


    def create
        @review = Review.new(review_params)
        
        if @review.save
            render json: {message: "Review was successfully created."}
        else
            render json: @review.errors, status: :unprocessable_entity
          
        end
    end


    def new
        @review = Review.new
        @order = Order.find(params[:id_order])
        @product = Product.find(params[:id_product])
      end

    def update
        @user = User.find(params[:id_user])
        @review = @user.reviews.find(params[:id])

        if @review.update(review_params)
            render json: {message: "Review was successfully updated."}
        else
            render json: @review.errors, status: :unprocessable_entity
        end
    end


    def destroy
        @user = User.find(current_user.id)
        @review = @user.reviews.find(params[:id])

        if @review.delete
            render json: {message: "Review was sucessfully deleted."}
        else
            render json: @review.errors, status: :unprocessable_entity
        end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>Proyecto Software</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.14.0/js/all.js"></script>

  </head>

  <body class="m-4">

    <% if user_signed_in? %>

      <% if current_user.email.include?("@admin") %>
        <% current_user.role = 1 %>
        <% current_user.save %>
      <% end %>


        <nav>

          <div id="navbarBasicExample" class="navbar-menu">
            <div class="navbar-start">

              <%= link_to current_user.name, edit_user_registration_path, class: "navbar-item" %>

              <% if current_user.admin? %>


                <%= link_to "Mis Reservas", orders_path, class: "navbar-item" %>


                <a class="navbar-item">
                  Ver Reseñas
                </a>

                <a class="navbar-item">
                  Ver Usuarios
                </a>

              <% else %>

                <%= link_to "Mis Reservas", order_path(current_user.id), class: "navbar-item" %>

                <%= link_to "Mis Reseñas", reviews_path, class: "navbar-item" %>

                <%= link_to "Productos", products_path, class: "navbar-item" %>

                

              <% end %>

              </div>

            <div class="navbar-end">
              <div class="navbar-item">
                <div class="buttons">
                  <%= button_to "Cerrar Sesión", destroy_user_session_path, method: :delete, class: "button is-primary"%>
                </div>
              </div>
            </div>

          </div>
        </nav>

    <% else %>

      <nav>

        <div class="navbar-end">
          <div class="navbar-item">
            <div class="buttons">

              <%= link_to new_user_registration_path, class: "button is-primary" do %>
                <strong>Registrarse</strong>
              <% end %>

              <%= link_to "Inicar Sesión", new_user_session_path, class: "button is-light" %>

            </div>
          </div>
        </div>

      </nav>

    <% end %>

    <% if flash[:notice] %>
      <p class="notice"><%= flash[:notice] %></p>
    <% end %>

    <% if flash[:alert] %>
      <p class="alert"><%= flash[:alert] %></p>
    <% end %>

    <%= yield %>
  </body>
</html>